### ISSUE TITLE
Shell closes immediately

### ISSUE THREAD

**Issue by besil** [alebcay/openlens-node-pod-menu#187]
Hello,

Thank you very much for this add-on.

Fresh install of MacOS, OpenLens and Node Pod menu.

Issue is: after I click on "Shell", terminal pops up and immediately closes.
In the developer view, I see the following log:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'loadCell')
    at t._forEachCell (xterm.js:1:155329)
    at t._drawBackground (xterm.js:1:155795)
    at t.onGridChanged (xterm.js:1:157734)
    at t.renderRows (xterm.js:1:147992)
    at t._renderRows (xterm.js:1:199538)
    at e._renderCallback (xterm.js:1:197163)
    at e._innerRefresh (xterm.js:1:37266)
    at xterm.js:1:37020
```

More Information about Lens:
OpenLens: 6.5.2-366
Extension API: 6.5.2
Electron: 22.3.3
Chrome: 108.0.5359.215
Node: 16.17.1

Extension version:
@alebcay/openlens-node-pod-menu version 0.1.2

OS Version: MacOS 14.4.1 (23E224) Sonoma

![image](https://github.com/alebcay/openlens-node-pod-menu/assets/7081486/5470dcc2-537d-4b60-81aa-938b1a1ecf92)

**Comment by hermaneyd** [comment]
Hi,
Same behaviour... =( Looks like common issue

**Comment by erniedavisAA** [comment]
works correctly on kubernetes 1.27.9, but fails on 1.28.10 if that helps troubleshooting efforts

**Comment by G-Groover** [comment]
Has there been any updates to correct this?  I'm experiencing the same

**Comment by ooagboola** [comment]
This fixed it for me 
https://github.com/alebcay/openlens-node-pod-menu/issues/159#issuecomment-1893058382
